name: Extract WHL ARMV7

on:
  push:
    tags: 'v*'

jobs:
  extract-wheel-armv7:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Source
        uses: actions/checkout@v2
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract WHL
        run: |
          mkdir "${PWD}/artifacts"
          docker create -ti --platform=linux/arm/v7 --name dummy ghcr.io/schnuffle/build-pikepdfwheel bash
          docker cp dummy:/usr/src/pikepdf/wheels ${PWD}/artifacts
          docker rm -f dummy

      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/artifacts"
      -
        name: Push Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifacts/wheels/*"
          token: ${{ secrets.GITHUB_TOKEN }}
