name: extract WHL

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Building and uploading pikepdf for armv7'
        # Default value if no value is explicitly provided
        default: 'beta'
        # Input has to be provided for the workflow to run
        required: true
        
jobs:
  buildwhl:
    runs-on: ubuntu-latest
    
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Upload dist
        run: |
          docker cp --platform=linux/arm64 ghcr.io/schnuffle/build-pikepdfwheel:latest:/usr/localsrc/pikepdf/wheels/*.whl .
      -
        name: Show downloads
        run: |
          ls -la .

