name: extract WHL

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Building and uploading pikepdf for armv7'
        # Default value if no value is explicitly provided
        default: 'v5.0.1'
        # Input has to be provided for the workflow to run
        required: true
        
jobs:
  buildwhl:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          ref: 'v1.0.0'
      - 
        name: Extract WHL
        run: |
          mkdir "${PWD}/artifacts"
          docker create -ti --name dummy ghcr.io/schnuffle/build-pikepdfwheel bash
          docker cp dummy:/usr/src/pikepdf/wheels/pikepdf-5.0.1-cp39-cp39-linux_armv7l.whl ${PWD}/artifacts
          docker rm -f dummy

      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/artifacts"
      -
        name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/pikepdf-5.0.1-cp39-cp39-linux_armv7l.whl
