name: extract WHL

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Building and uploading pikepdf for armv7'
        # Default value if no value is explicitly provided
        default: 'beta'
        # Input has to be provided for the workflow to run
        required: true
        
jobs:
  buildwhl:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Extract WHL
        run: |
          mkdir "${PWD}/artifacts"
          docker cp ghcr.io/schnuffle/build-pikepdfwheel:latest:/usr/src/pikepdf/wheels/*.whl ${PWD}/artifacts

      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/artifacts"
