name: Extract WHLS for  ARMV7/64

on:
  push:
    tags: 'v*'

jobs:
  extract-wheels:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout Source
        uses: actions/checkout@v2
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Extract WHL ARMV7
        run: |
          mkdir "${PWD}/artifacts"
          mkdir -p "${PWD}/artifacts/jbig2enc"
          docker create -ti --platform=linux/arm/v7 --name dummy ghcr.io/schnuffle/build-pikepdfwheel bash
          docker cp dummy:/usr/src/pikepdf/wheels ${PWD}/artifacts
          docker cp dummy:/usr/src/jbig2enc ${PWD}/artifacts/jbig2enc
          tar czf ${PWD}/artifacts/jbig2enc-armv7.tgz ${PWD}/artifacts/jbig2enc
          rm -fR ${PWD}/artifacts/jbig2enc
          docker rm -f dummy
      - 
        name: Extract WHL ARM64
        run: |
          mkdir -p "${PWD}/artifacts/jbig2enc"
          docker create -ti --platform=linux/arm64 --name dummy ghcr.io/schnuffle/build-pikepdfwheel-arm64:latest bash
          docker cp dummy:/usr/src/pikepdf/wheels ${PWD}/artifacts
          docker cp dummy:/usr/src/jbig2enc ${PWD}/artifacts/jbig2enc
          tar czf ${PWD}/artifacts/jbig2enc-armv7.tgz ${PWD}/artifacts/jbig2enc
          rm -fR ${PWD}/artifacts/jbig2enc          
          docker rm -f dummy
          
      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/artifacts/wheels"
          ls -al "${PWD}/artifacts"
      -
        name: Push Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./artifacts/wheels/*.whl,./artifacts/*.tgz"
          token: ${{ secrets.GITHUB_TOKEN }}
