name: extract WHL

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Building and uploading pikepdf for armv7'
        # Default value if no value is explicitly provided
        default: 'beta'
        # Input has to be provided for the workflow to run
        required: true
        
jobs:
  buildwhl:
    runs-on: ubuntu-18.04
    steps:
      - 
        name: Run images
        uses: uraimo/run-on-arch-action@v2.1.1
        with:
          arch: armv7
          distro: ghcr.io/schnuffle/build-pikepdfwheel
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          shell: /bin/sh
          run: |
            ls -la /usr/src
            ls -la /usr/src/pikepdf
            #cp /usr/src/pikepdf/wheels/*.whl "/artifacts/"
            echo "Produced artifact at /artifacts/"
      - name: Show the artifact
        # Items placed in /artifacts in the container will be in
        # ${PWD}/artifacts on the host.
        run: |
          ls -al "${PWD}/artifacts"
